config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "pages#home"
  resources :projects
  #  Add route to select a project
  post 'select_project', to: 'projects#select_project', as: 'select_project'


  resources :tasks do
    post 'comments', to: 'comments#create'
    resources :comments, only: [:edit, :update, :destroy]

  end
  
  


end

app/models/task.rb
class Task < ApplicationRecord 
    has_rich_text :description
    has_many :comments, foreign_key: 'commentable_id', dependent: :destroy
    belongs_to :member, class_name: 'User', foreign_key: 'member_id'    
    belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
    validates :title, :description, :creator_id, :project_id, presence: true
    self.per_page = 3
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :authenticate_project, only: [:edit, :update, :destroy]
    include ApplicationHelper
    
    def index
      @tasks = Task.includes(:creator, :member).where(project_id: current_project_id).paginate(page: params[:page])
    
      respond_to do |format|
        format.html
        format.js
      end
    end
    

    def new
        @task=Task.new
    end

    def create
        @task=Task.new(task_params)
        @task.creator_id=current_user.id
        @task.project_id=current_project_id
        if @task.save
            flash[:notice] = "Task was created successfully."
            redirect_to tasks_path
        else
           render 'new'
        end

    end

    def edit

    end

    def update
        if @task.update(task_params)
          flash[:notice] = "Task was updated successfully." unless request.xhr?
          respond_to do |format|
            format.html { redirect_to tasks_path }
            format.json { render json: { success: true } }
          end
        else
          flash.now[:notice] = "Task update failed. #{@task.errors.full_messages}"
          redirect_to tasks_path
        end
      end
      
    
    def show
        @comments = Comment.where(commentable_id: params[:id]).order(created_at: :desc)
    end

    def destroy
        @task.destroy
        redirect_to tasks_path, notice: 'Task deleted successfully.'
    end

    def set_task
        @task=Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:title, :description, :member_id, :project_id, :status, :priority)
    end


    def authenticate_project
        task = Task.find(params[:id])
        if not (current_project_id==task.project_id)
            flash[:notice]= "you are not authorized to perform this action"
          redirect_to tasks_path
        end
      end
      


end

app/views/tasks/_comment.html.erb
<div class="card">
  <div class="card-body">
    <strong><%= comment.user.name %>: </strong>
    <%= comment.content %>
    <% if can? :update, comment %>
      <%= link_to "Edit", edit_task_comment_path(@task, comment), class: "btn btn-outline-info" %>
    <% end %>
    <% if can? :destroy, comment %>
      <%= button_to "Delete", task_comment_path(@task, comment), method: :delete, class: "btn btn-outline-danger" %>
    <% end %>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="container">
  <% if @task.errors.any? %>
    <h2>The following errors prevented the project from being saved</h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @task, class: "shadow p-3 mb-3 custom-row rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of the task"%>
          </div>
        </div>
        <br>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.rich_text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of task" %>
          </div>
        </div>

        <br>
        
        <div class="form-group row">
          <%= f.label :member, class: "col-2 col-form-label text-light" %> 
          <div class="col-10"> 
          <%= f.collection_select :member_id, Project.find(current_project_id).members, :id, :name, { prompt: "Select one" }, { class: "form-control" } %>
          </div>
        </div>
        <br>
        <div class="form-group row">
          <%= f.label :priority, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <div class="form-check form-check-inline">
              <%= f.radio_button :priority, 1, class: "form-check-input" %>
              <%= f.label :priority_high, "High", class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :priority, 2, class: "form-check-input" %>
              <%= f.label :priority_medium, "Medium", class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :priority, 3, class: "form-check-input" %>
              <%= f.label :priority_low, "Low", class: "form-check-label" %>
            </div>
          </div>
        
        <br>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <h5 class="card-title"><%= link_to task.title, task_path(task), class: "text-success" %></h5>
        <%= link_to Project.find(task.project_id).name, project_path(Project.find(task.project_id)), class: "badge rounded-pill text-bg-info mr-1" %>
      </div>
      <div class="card-body">
        <%= task.description %>
        <p class="card-text">Manager: <%= task.creator.name %></p>
        <p class="card-text">Assigned to: <%= task.member.name %></p>
        <%= link_to "View", task_path(task), class: "btn btn-outline-success" %>
        <% if can? :update, task %>
          <%= link_to "Edit", edit_task_path(task), class: "btn btn-outline-info" %>
        <% end %>
        <% if can? :destory, task %>
          <%= button_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="card-footer">
        <div class="form-check form-check-inline">
          <%= radio_button_tag "status_#{task.id}", "todo", task.status == 'todo', class: "form-check-input", data: { task_id: task.id } %>
          <label class="form-check-label btn btn-outline-primary" for="status_<%= task.id %>">Todo</label>
        </div>
        <div class="form-check form-check-inline">
          <%= radio_button_tag "status_#{task.id}", "in-process", task.status == 'in-process', class: "form-check-input", data: { task_id: task.id } %>
          <label class="form-check-label btn btn-outline-warning" for="status_<%= task.id %>">In Process</label>
        </div>
        <div class="form-check form-check-inline">
          <%= radio_button_tag "status_#{task.id}", "done", task.status == 'done', class: "form-check-input", data: { task_id: task.id } %>
          <label class="form-check-label btn btn-outline-success" for="status_<%= task.id %>">Done</label>
        </div>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(task.created_at) %> ago,
          edited <%= time_ago_in_words(task.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1 class="text-center mt-4">Edit task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Listing all tasks</h1>
  <div class="container">
    <div id="tasks">
      <%= render @tasks %>
    </div>
    <div id="pagination" class='hidden'>
      <%= will_paginate @tasks %>
    </div>
  </div>
</div>
<div id="next_data" data-next-page="<%= @tasks.next_page %>"></div>

app/views/tasks/index.js.erb
<% if @tasks.present? %>
  $('#tasks').append('<%= j render @tasks %>');
  $('.pagination').replaceWith('<%= j will_paginate @tasks %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Details of task</h1>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @task.creator.name %>
          </div>

          <div class="card-body">
            <h5 class="card-title"><%= link_to @task.title, class: "text-success" %></h5>
            <p class="card-text">Assigned to: <%= @task.member.name %></p>
            <%= @task.description %>
          </div>
          <div class="card-footer text-muted">
            <small>
              Created <%= time_ago_in_words(@task.created_at) %> ago, edited <%= time_ago_in_words(@task.updated_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="page-content", class="container">
  <div class="row justify-content-md-center">
    <div class="col-10 mt-4">
      <div class="container">
              <%if not @comments.any?%>
             <h1 class="text-center mt-4">Add a Comment</h1>
             <%end%>
              <div id="comment-form">
                  <%= form_with model: Comment.new, url: task_comments_path(@task), method: :post do |form| %>
                  <%= form.rich_text_area :content, class: "form-control", placeholder: "Enter comment" %>
                  <%= form.submit "Add Comment", class: "btn btn-outline-info", data: { disable_with: "Submitting..." } %>
                    <% end %>
              </div>
              <br>
                   <% if @comments.any? %>
                      <div id="comments">
                        <%= render partial: 'tasks/comment', collection: @comments %>
                      </div>
                  <%end%>
      </div>
    </div>
  </div>
</div>