config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "pages#home"
  resources :projects
  #  Add route to select a project
  post 'select_project', to: 'projects#select_project', as: 'select_project'


  resources :tasks do
    post 'comments', to: 'comments#create'
    resources :comments, only: [:edit, :update, :destroy]

  end
  
  


end

app/models/project.rb
class Project < ApplicationRecord 

    has_rich_text :description
    belongs_to :creator, class_name: 'User'
    has_many :tasks, foreign_key: 'project_id', dependent: :destroy
    has_many :project_members,  dependent: :destroy
    has_many :members, through: :project_members, source: :user,  dependent: :destroy
    validates :name, presence: true
    validates :description, presence: true
    self.per_page = 3

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    load_and_authorize_resource

  

    def index
        if current_user.role == "manager"
          @projects = current_user.created_projects.includes(:creator).paginate(page: params[:page])
        else
          @projects = current_user.projects.includes(:creator).paginate(page: params[:page])
        end
        respond_to do |format|
          format.html
          format.js
        end
      end
      

    def new
        @project=Project.new

    end


    def select_project
        project_id = params[:project_id]
        cookies[:selectedProjectId] = project_id
        redirect_to tasks_path
      end



    def show
    end

    def create
        @project=Project.new(project_params)

        @project.creator_id=current_user.id
        
        if @project.save
        flash[:notice]= "Project added Successfully"
        redirect_to tasks_path

        else
         render 'new'
        end
    end


    def edit
    end

    def update
      
        if @project.update(project_params)
            flash[:notice] = "Project was updated successfully."
            redirect_to projects_path
        else
            flash[:alert]= "Project not updated."
            redirect_to projects_path
        end
    end

   
    def destroy
        @project.destroy
        redirect_to projects_path, notice: 'Project deleted successfully.'
      end
      

    
    def project_params
        params.require(:project).permit(:name, :description, member_ids: []).tap do |whitelisted|
            whitelisted[:description] = params[:project][:description]
        end
        
    end
    

    def set_project
        @project=Project.find(params[:id])
      end
end

app/views/projects/_form.html.erb
<div class="container">
  <% if @project.errors.any? %>
    
    <h2>The following errors prevented the project from being saved</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @project, class: "shadow p-3 mb-3 custom-row rounded", local: true, data: { turbo: false }) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of the project" %>
          </div>
        </div>
        <br>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light " %>
          <div class="col-10"> 
            <%= f.rich_text_area :description, class: "form-control shadow rounded trix-content", placeholder: "Description of project" %>
          </div>
        </div>

        <br>

        <div class="form-group row">
          <%= f.label :member, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
          <%= f.collection_select :member_ids, User.where(role: "member"), :id, :name, {prompt: " make your selection one "}, { multiple: true , class: "form-control" } %>


          </div>
        </div>
        
        <br>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <h5 class="card-title"><%= link_to project.name, project_path(project), class: "text-success" %></h5>
      </div>
      <div class="card-body">
        <%= project.description %>
        <%= render_attachments(project.description) %>
        <p class="card-text">Manager: <%= project.creator.name %></p>
        <p class="card-text">Members: <%= project.project_members.length %></p>
        <%= link_to "View", project_path(project), class: "btn btn-outline-success" %>

        <% if can? :update, project %>
          <%= link_to "Edit", edit_project_path(project), class: "btn btn-outline-info" %>
        <% end %>
        <% if can? :destory, project %>
          <%= button_to "Delete", project_path(project), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(project.created_at) %> ago, edited <%= time_ago_in_words(project.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Listing all projects</h1>
  <div class="container">
    <div id="projects">
      <%= render @projects %>
    </div>
    <div id="pagination" class='hidden'>
      <%= will_paginate @projects %>
    </div>
  </div>
</div>
<div id="next_data" data-next-page="<%= @projects.next_page %>"></div>

app/views/projects/index.js.erb
<% if @projects.present? %>
  $('#projects').append('<%= j render @projects %>');
  $('.pagination').replaceWith('<%= j will_paginate @projects %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/projects/new.html.erb
<h1 class="text-center mt-4">Enter details of project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Details of project</h1>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @project.creator.name %>
          </div>

          <div class="card-body">
            <h5 class="card-title"><%= link_to @project.name, class: "text-success" %></h5>
            <%= @project.description %>
          </div>

          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@project.created_at) %> ago,
            edited <%= time_ago_in_words(@project.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>