config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "pages#home"
  resources :projects
  #  Add route to select a project
  post 'select_project', to: 'projects#select_project', as: 'select_project'


  resources :tasks do
    post 'comments', to: 'comments#create'
    resources :comments, only: [:edit, :update, :destroy]

  end
  
  


end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">DevTrack</a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item">
          <%= link_to "Home", root_path,class: 'nav-link' %>
        </li>
            <li class="navbar-item-right">
            <%= link_to "Projects", projects_path,class: 'nav-link' %>
            </li>
            <% if user_signed_in? && current_user.role == "manager" %>
            <li class="navbar-item-right">
            <%= link_to "Add Project", new_project_path,class: 'nav-link' %>
            </li>
            <%end%>
            

            <li class="navbar-item-right">
            <%= link_to "Tasks", tasks_path,class: 'nav-link' %>
            </li>

            <li class="navbar-item-right">
            <%= link_to "Add Task", new_task_path,class: 'nav-link' %>
            </li>
        
        <li class="navbar-item-right">
          <% if user_signed_in? %>
          <%= form_tag select_project_path, method: :post, class: "nav-link", id: "project-form" do %>
            <%= select_tag :project_id, options_from_collection_for_select(current_user.role == "manager" ? current_user.created_projects : current_user.projects, :id, :name, cookies[:selectedProjectId]), prompt: "Select one", class: "form-control", onchange: "submit()" %>
          <% end %>
          
           <% end %>     
          </li>   

            <%if user_signed_in?%>
            <li class="navbar-item-right">
            <%= button_to "Log out", destroy_user_session_path,:method => :delete, class: 'nav-link btn-link'%>
            </li>

            <li class="navbar-item-right">
              <a href="#" class="nav-link notification"><%= notification_count %></a>
            </li>
            
            <li class="navbar-item-right">
            <span class="white-text">[ <%= current_user.name %>]</span>
            </li>


            <%else%>
            <li class="navbar-item-right">
            <%= link_to "Login", user_session_path,class: 'nav-link' %>
            </li>
            <%end%>


        
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render "layouts/navbar" %>
  <br/>

  <% if notice %>
    <div class="flash-notice-container">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="flash-alert-container">
      <%= alert %>
    </div>
  <% end %>

  <%= yield %>
</body>
</html>